id: I502B2CB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T01:56:00+00:00'
last_modified: '2022-06-08T17:34:57.770187+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2327
  title: རྫོགས་པ་ཆེན་པོ་མུ་ཏིག་ཕྲེང་རྒྱུད་གསལ་བྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A234:
      image_group_id: I1CZ2336
      title: ''
      total_pages: 550
      order: 1
      base_file: A234.txt
    '2112':
      image_group_id: I1CZ2337
      title: ''
      total_pages: 206
      order: 2
      base_file: 2112.txt
    05EE:
      image_group_id: I1CZ2338
      title: ''
      total_pages: 492
      order: 3
      base_file: 05EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
