id: P010795
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-20 10:24:52.173351
source_metadata:
  id: bdr:W1CZ2327
  title: རྫོགས་པ་ཆེན་པོ་མུ་ཏིག་ཕྲེང་རྒྱུད་གསལ་བྱེད
  author: ''
  volumes:
    994b7951d6f24d60860ff99fa057a7d4:
      image_group_id: I1CZ2336
      title: ''
      volume_number: 1
      total_pages: 550
      base_file: v001.txt
    715c53ae717c454c9361d5195fa0d8b6:
      image_group_id: I1CZ2337
      title: ''
      volume_number: 2
      total_pages: 206
      base_file: v002.txt
    4243572d93d8452882e4cef21f1db1e9:
      image_group_id: I1CZ2338
      title: ''
      volume_number: 3
      total_pages: 492
      base_file: v003.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
